### ISSUE TITLE
Question about the Intensity-based augmentations

### ISSUE THREAD

**Issue by Hugo-cell111** [ZhenZHAO/iMAS#1]
Hi! I just read the paper of iMAS and find the formula 8. Theoretical speaking, the harder the sample is, the larger its gamma is. So for the hard samples, it is inappropriate to assign large proportion of strong augmentation. For the easy samples, the strong augmentation can be added without too much concern. So I think the correct formula is written as: A_s <- (1 - gamma) * A_s + gamma * A_w. But in the paper it is A_s <- (1 - gamma) * A_w + gamma * A_s. So I am confused by it. Could you please explain it? Thanks a lot!

**Comment by ZhenZHAO** [comment]
Sorry about that. You are right. In my first draft I use the easiness (also in the code), I will correct it later.
