### ISSUE TITLE
关于无标签数据损失计算问题

### ISSUE THREAD

**Issue by hhuishi** [ZhenZHAO/iMAS#11]
你好，我看到代码中，关于无标签数据集，仅是对该类数据进行强弱增强，然后利用原有标签进行损失计算对吗？但是随机裁剪操作会不会影响数据与标签的对应关系，进而影响实验结果呢？

**Comment by ZhenZHAO** [comment]
哎呦，这也是半监督分类和分割一个不同的地方，因为分类整附图出一个语义，想怎么aug都行，但是分割不行。

aug可以简单分为三类，geometrical，intensity(color)-based, mixup-based. 像您说的随机裁剪这种应该放在第一类geometrical aug,这类aug是需要对image和对应的label同时做augmentation。mixup-based那种也是，因为图像对应的pixel的语义(prediction)改变了， 需要修改对应的label。

intensity or color 这种只是修改了pixel的值，并没有改变pixel的语义，所以不需要修改对应的label。

Hope it helps.
