### ISSUE TITLE
关于dist.all_gather的疑问

### ISSUE THREAD

**Issue by Hugo-cell111** [ZhenZHAO/iMAS#12]
您好！请问您在代码里用dist.all_gather这个函数的时候，会出现以下几个问题吗？（1）显存利用率卡在100%，训练进程卡住；（2）训练不稳定，中途可能会报nccl相关的bug. 谢谢！

**Comment by ZhenZHAO** [comment]
不好意思，我没碰到过~ 这是个挺常用的api吧

**Comment by Aawen123** [comment]
> 您好！请问您在代码里用dist.all_gather这个函数的时候，会出现以下几个问题吗？（1）显存利用率卡在100%，训练进程卡住；（2）训练不稳定，中途可能会报nccl相关的bug. 谢谢！

请问这个问题解决了吗？我也遇到了同样的问题，期待您的解答。谢谢
