### ISSUE TITLE
关于GPU的使用和推理细节的疑问

### ISSUE THREAD

**Issue by Hugo-cell111** [ZhenZHAO/iMAS#13]
您好！请问您这份工作是在多少张什么类型的GPU上进行的？另外我看到您对cityscapes数据集进行推理的时候，采取的是sliding windows的方法。我自己用sliding windows推理（代码和UniMatch完全一致），在4张V100进行推理，需要大约3分钟，但是看您的日志只需要半分钟。想问一下有可能哪里出现了问题？谢谢！

**Comment by ZhenZHAO** [comment]
citys 应该用了8片V100. （其实你看log也能看出来）
