### ISSUE TITLE
dist.all_reduce(loss)的目的

### ISSUE THREAD

**Issue by Hugo-cell111** [ZhenZHAO/iMAS#2]
作者你好！在[这行代码](https://github.com/ZhenZHAO/iMAS/blob/main/train_semi.py#L557)里，我看到你使用了dist.all_reduce，但是一般来说使用了DDP就不需要再把各GPU上的值给汇总起来了。请问这行代码的作用是什么呢？

**Comment by ZhenZHAO** [comment]
Hi, 应该是为了统计总loss，同样地方式，还统计了hardness。
