### ISSUE TITLE
关于无标签数据的增强

### ISSUE THREAD

**Issue by YUCOCOCS** [ZhenZHAO/iMAS#3]
您好，感谢你卓越的工作，我有一个问题是关于你在网络训练时使用分布式训练，那么原文中批处理是16，如果用8张卡的话，那么每张卡就2个无标签图片，那么增强就只能在两个图片上进行增强嘛？因为感觉每个gpu都只是处理自己的数据。

**Comment by ZhenZHAO** [comment]
Hi，就是像您说的这样。所以，personally，这个工作其实性能可以更高。而且这个工作中augmentaion应该用的再强一些效果道理上会更好，还有就是citys上ohem loss的设置应该调调。相比AugSeg，这个工作思路是，直接把aug弄到最强，然后adaptive的用, 然后强弱mix，难易mix。希望对您有帮助~~
