### ISSUE TITLE
关于paper中Model-adaptive strong augmentations公式表述

### ISSUE THREAD

**Issue by Herschel555** [ZhenZHAO/iMAS#4]
作者您好，感谢您出色的工作！在阅读paper时有处疑惑，在CVPR 2023 Open Access版本的paper中，3.3.1节中instance-based augmentations章节中的公式(7)：
![image](https://github.com/ZhenZHAO/iMAS/assets/64767709/85eaeb6b-ceb8-4ac2-9d69-70ac8d967afb)
是否应该修改为：
![image](https://github.com/ZhenZHAO/iMAS/assets/64767709/16fa608c-263d-41fa-8120-b736e317f9ec)
即，若当前样本较为困难（对应的$\gamma$较大）时，对应需要为弱增强版本分配更大的比例来弱化增强程度，期待您的解惑！

**Comment by ZhenZHAO** [comment]
Hi, 这个公式确实写错了，，also @ https://github.com/ZhenZHAO/iMAS/issues/1

我后面更新一下arxiv，非常抱歉

**Comment by Herschel555** [comment]
感谢回复！抱歉之前没有看到已提的issue 1！
